'''
25/04/2020

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def fibonacci(number):
    if number == 0:
        return 1
    elif number == 1:
        return 2
    else:
        return fibonacci(number-1) + fibonacci(number-2)

n = 0
sum = 0
while fibonacci(n) <= 4000000:
    if not fibonacci(n) % 2:
        sum += fibonacci(n)
    n += 1

print(sum)